services:
  panel:
    build:
      context: .
    container_name: node-nexus-panel-dev
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
      - VITE_API_KEY=
      - VITE_PANEL_LOGIN=admin
      - VITE_PANEL_PASSWORD=password
    restart: unless-stopped
