export { api, ApiRequestError } from './client'
export { nodesApi } from './nodes'
export { commandsApi } from './commands'
export { scriptsApi } from './scripts'
export { apiKeysApi } from './settings'
export { dockerApi } from './docker'
export { composeApi } from './compose'
export { auditApi } from './audit'
export { searchApi } from './search'
export { favoritesApi } from './favorites'
export { configApi } from './config'
export { templatesApi } from './templates'
export { healthApi } from './health'
export { authApi } from './auth'
export { usersApi } from './users'
export { eventsClient, EventsClient } from './events'
export type * from './types'
// Deprecated: dashboardApi and notesApi removed in v2 (no spec)
